# Source: https://github.com/marketplace/actions/github-readme-youtube-cards
name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCKMWXwHYoy920OFEN_BM5VQ
          comment_tag_name: YOUTUBE-CARDS
          max_videos: 3
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
